# digit modifier for current currency / example: 1000 = 4 digits
base_digit: 5

# output csv setting
output_delimiter: "\t"  # it returns error when using '\t' or just \t
output_directory: ./../output/
output_base_filename: daily-dcs-converted
output_filename_time_format: '%Y-%m-%d-%H%M%S'

# define kinds of keywords
keywords: e, sv, svv, w, q, qq, qqq, tr, pk, xp, t, v, sc, r, f, hm, d, dd, i, ps, u, z, j, pn
int_keywords: u, z, j, pn